server:
  tomcat:
    uri-encoding: UTF-8  # 默认
    # 优化Spring Boot
    connection-timeout: 5000ms
    threads:
      max: 1000
      min-spare: 20

  port: 8080
  servlet:
    context-path: /not_just_note

spring:
  datasource:
    # https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
    # https://blog.csdn.net/yunnysunny/article/details/8657095
    druid:
      # https://blog.csdn.net/weixin_55181056/article/details/124164782 解决MySQL saveBatch插入效率低下
      url: jdbc:mysql://localhost:3306/not_just_note?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: Astroline^...?
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000

      # Oracle
      # validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: Astroline
        login-password: Eve...?

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false

        wall:
          enabled: true
          config:
            multi-statement-allow: true
            drop-table-allow: false
  redis:
    open: true
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    client-type: lettuce
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.niyredra.notjustnote.modules
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
